charts/nopo11y-stack/Chart.yaml, charts/nopo11y-stack/dashboards/slo-details.json, charts/nopo11y-stack/templates/alerts.yaml, charts/nopo11y-stack/values.yaml
Description:
- Updated slo-details dashboard to show NaN in panels when there is NaN value returned.
- Updated Memory and CPU utilization alerts to remove the metrics which are not required.
- Added the comment in nopo11y health check values about the option env variables
- Updated the helm chart version to 1.1.1
=> Minor changes in nopo11y-stack

charts/nopo11y/Chart.yaml, charts/nopo11y/templates/_helpers.tpl, charts/nopo11y/templates/defaultAlerts.yaml, charts/nopo11y/templates/defaultDashboard.yaml, charts/nopo11y/templates/defaultSLOs.yaml
Changes:
- Added helper template to read app label and deployment name in nopo11y alerts, dashboard and SLOs.
=> Added helpers in nopo11y chart

tools/system-health-check/health_check.py, tools/system-health-check/kh_client.py
Changes
- Updated prometheus pod health check quires to skip pods which don't have any resource requests and limits set.
- Corrected failure message reporting to kuberhealthy
=> Health check program changes

charts/nopo11y/Chart.yaml, charts/nopo11y/templates/defaultAlerts.yaml, charts/nopo11y/templates/defaultDashboard.yaml, charts/nopo11y/templates/defaultSLOs.yaml, charts/nopo11y/values.yaml
Updates
- Added support to add cluster label in metrics if deploying nopo11y in multi cluster environment.
=> Nopo11y multicluster support

charts/nopo11y/Chart.yaml, charts/nopo11y/templates/_helpers.tpl, charts/nopo11y/templates/alerts.yaml, charts/nopo11y/templates/dashboards.yaml, charts/nopo11y/templates/slos.yaml, charts/nopo11y/values.yaml
Updates:
- Added namespace label in istio and nginx metrics
- Removed istioMetrics and nginxIngressMetrics key from values and added apiGateway key
=> Namespace label addition in istio and nginx metrics

charts/nopo11y-stack/Chart.yaml, charts/nopo11y-stack/charts/nopo11y-operator/Chart.yaml, charts/nopo11y-stack/charts/nopo11y-operator/templates/_helpers.tpl, charts/nopo11y-stack/charts/nopo11y-operator/templates/clusterrole.yaml, charts/nopo11y-stack/charts/nopo11y-operator/templates/clusterrolebinding.yaml, charts/nopo11y-stack/charts/nopo11y-operator/templates/crd.yaml, charts/nopo11y-stack/charts/nopo11y-operator/templates/deployment.yaml, charts/nopo11y-stack/charts/nopo11y-operator/templates/service.yaml, charts/nopo11y-stack/charts/nopo11y-operator/templates/serviceaccount.yaml, charts/nopo11y-stack/charts/nopo11y-operator/values.yaml, charts/nopo11y-stack/values.yaml, tools/nopo11y-operator/Dockerfile, tools/nopo11y-operator/README.md, tools/nopo11y-operator/get_services_deployments.py, tools/nopo11y-operator/requirements.txt, tools/nopo11y-operator/templates/nopo11y-op-alerts.yaml, tools/nopo11y-operator/templates/nopo11y-op-dashboard.yaml, tools/nopo11y-operator/templates/nopo11y-op-slo-availability.yaml, tools/nopo11y-operator/templates/nopo11y-op-slo-latency.yaml
Updates:
- Added nopo11y operator helm chart as a dependent chart in nopo11y-stack
- Added code of nopo11y operator
=> Nopo11y operator addition

tools/nopo11y-operator/templates/nopo11y-op-dashboard.yaml
- Count of the error logs will be visible in the overview dashboard
- Logs panel will now show logs with error and exception
=> Updated logs panel in the overview dashboard

tools/nopo11y-operator/templates/nopo11y-op-dashboard.yaml
- Combined request count and response time panels
- Added 4xx error rate indicator
- Shifted logs error count panel to the top
- Combined cpu request and limit panels
- Combined memory request and limit panels
- Removed success-error rate panel
- Expanded error logs panel
=> Dashboard improvements

.github/workflows/chart-release.yaml, .github/workflows/health-check-build.yaml, .github/workflows/operator-build.yaml
Added initial github workflow for building images for tools, we will upgrade workflow in the subsequent releases.
=> Workflow changes for building images for tools

charts/nopo11y/README.md
Updated nopo11y helm chart documentation
=> Nopo11y helm chart documentation update

charts/nopo11y-stack/Chart.yaml, charts/nopo11y-stack/templates/_helpers.tpl
Update:
- Updated logic to get a grafana server root url to create ingress
=> Nopo11y-stack ingress changes - updated logic to get grafana root url for grafana ingress creation

charts/nopo11y-stack/README.md
Updates:
- Added instructions on how to access nopo11y-stack components
=> Nopo11y-stack - how to access documentation

charts/nopo11y-stack/Chart.yaml, charts/nopo11y-stack/README.md, charts/nopo11y-stack/dashboards/kubernetes-event-exporter.json, charts/nopo11y-stack/templates/_helpers.tpl, charts/nopo11y-stack/templates/dashboards.yaml, charts/nopo11y-stack/values.yaml
Update:
- Added kubernetes event exporter chart
- Added grafana dashboard for kubernetes event exporter
- Updated chart version to 1.5.0
=> Kubernetes event exporter chart addition

charts/nopo11y-stack/Chart.yaml, charts/nopo11y-stack/templates/_helpers.tpl, charts/nopo11y-stack/templates/istio-gateway.yaml
Updates:
- Enabled SSL re-direction in istio gateway if TLS enabled
- Corrected sub chart name of kiali in _helpers.tpl
- Updated chart version to 1.5.2 from 1.5.1
=> Enabled SSL re-direction in istio gateway

charts/nopo11y-stack/Chart.yaml, charts/nopo11y-stack/README.md, charts/nopo11y-stack/values.yaml
Upgraded below charts to latest versions
- grafana-loki
- promtail
- kiali-server
- kubernetes-event-exporter
=> Loki, promtail, kiali and event exporter chart upgrade

charts/nopo11y-stack/Chart.yaml, charts/nopo11y-stack/templates/nopo11y-health-check.yaml, charts/nopo11y-stack/values.yaml
Updates:
- Added option to add custom labels to pods of nopo11y health checks
- Updated chart version to 1.7.2
=> Added option for adding custom labels for nopo11y health checks

charts/nopo11y-stack/samples/azure-nopo11y-stack-sample-values-with-private-docker-registry.yaml, charts/nopo11y-stack/samples/azure-nopo11y-stack-sample-values.yaml, charts/nopo11y-stack/samples/gcp-nopo11y-stack-sample-vaules-with-private-docker-registry.yaml, charts/nopo11y-stack/samples/gcp-nopo11y-stack-sample-vaules.yaml
Updates
- Created separate values file public and private docker registry
- Corrected formatting and typos
=> Changes to nopo11y-stack sample values file

charts/nopo11y-stack/Chart.yaml, charts/nopo11y-stack/values.yaml
Updates:
- upgraded thanos chart to latest version 15.9.2
- updated nopo11y-stack chart version to 2.1.0
=> Thanos upgrade

charts/nopo11y-stack/Chart.yaml, charts/nopo11y-stack/templates/kiali-secret.yaml, charts/nopo11y-stack/values.yaml
Updates:
- Added capability to create kiali secret if oidc-secret is present in values
- Updated chart version to 2.2.0
=> Create kiali secret if oidc-secret is present

charts/nopo11y-stack/samples/azure-nopo11y-stack-sample-values-with-private-docker-registry.yaml, charts/nopo11y-stack/samples/azure-nopo11y-stack-sample-values.yaml, charts/nopo11y-stack/samples/gcp-nopo11y-stack-sample-vaules-with-private-docker-registry.yaml, charts/nopo11y-stack/samples/gcp-nopo11y-stack-sample-vaules.yaml
Updates:
- Streamlined sample values files
=> Streamlined sample values files

charts/nopo11y-stack/Chart.yaml, charts/nopo11y-stack/values.yaml
Added global rules to mask sensitive information such as ssn, creditcard number, email, ip, mobile number using promtail replace function
=> Added global rules to mask sensitive information using promtail

tools/nopo11y-operator/requirements.txt
This will fix https://github.com/znsio/nopo11y/security/dependabot/4 and https://github.com/znsio/nopo11y/security/dependabot/3
=> Security Fix: Upgraded Jinja2 to 3.1.5

tools/system-health-check/health_check.py
Restructured node health check query to optimize the health check
=> Restructured node health check prometheus query

tools/system-health-check/health_check.py
Updated node health check to remove duplicate nodes from the result
=> Updated node health check to remove duplicate nodes

charts/namespace-creator/Chart.yaml, charts/namespace-creator/templates/namespace.yaml, charts/namespace-creator/templates/resourcequota.yaml, charts/namespace-creator/values.yaml
Added namespace creation chart with resource quota support
=> Added namespace creation chart with resource quota support

.github/workflows/chart-generator-build.yaml, tools/chart-generator/dockerfile, tools/chart-generator/scripts/config/.npmrc, tools/chart-generator/scripts/config/settings.yaml, tools/chart-generator/scripts/lib/bootstrap.sh, tools/chart-generator/scripts/lib/config.sh, tools/chart-generator/scripts/lib/constants.sh, tools/chart-generator/scripts/lib/ctk/init-ctk-run.sh, tools/chart-generator/scripts/lib/ctk/run-api-ctk.sh, tools/chart-generator/scripts/lib/display/basic.sh, tools/chart-generator/scripts/lib/display/colored.sh, tools/chart-generator/scripts/lib/init.sh, tools/chart-generator/scripts/lib/o11y/services.sh, tools/chart-generator/scripts/lib/oda/apis-spec.sh, tools/chart-generator/scripts/lib/oda/apis.sh, tools/chart-generator/scripts/lib/oda/common.sh, tools/chart-generator/scripts/lib/oda/component-spec.sh, tools/chart-generator/scripts/lib/oda/component.sh, tools/chart-generator/scripts/lib/paths.sh, tools/chart-generator/scripts/lib/util.sh, tools/chart-generator/scripts/start.sh
=> adding scripts that help generate nopo11y helms from an ordinary or tmf based microservice 

charts/meta-chart/templates/virtual-service.yaml
Fixed rewrite syntax in virtual-service.yaml
=> Fixed rewrite syntax in virtual-service.yaml

charts/meta-chart/templates/virtual-service.yaml
Added missing slash in virtual-service.yaml
=> Added missing slash in virtual-service.yaml

charts/meta-chart/Chart.yaml, charts/meta-chart/values.yaml
Updated docker image links for kafka, grpc and graphql
=> Updated docker image links for kafka, grpc and graphql
